### ISSUE TITLE
Update of tutorials/examples/docs/spec to support remediation process modeled via Shipyard v.0.2

### ISSUE THREAD

**Issue by johannes-b** [keptn/examples#166]
Follow-up on: keptn/examples#165

After implementing keptn/keptn#3682 and keptn/keptn#3683, the remediation process is modeled in the shipyard file of a project. This has implications on all tutorials and examples used to demo the use-case. 

**Definition of Done:** Update all artifacts related to the documentation of the remediation use-case: 
- [x] Examples: https://github.com/keptn/examples/tree/master/onboarding-carts (handled in #165) -> https://github.com/keptn/examples/pull/169 )
- [ ] Tutorials for remediation: https://github.com/keptn/tutorials/tree/master/site/tutorials (handled in #165) -> https://github.com/keptn/tutorials/pull/164 )
- [x] Readme of remediation-service: https://github.com/keptn/keptn/tree/master/remediation-service (handled in the keptn core issue, already updated)
- [x] Docu: https://keptn.sh/docs/0.8.x/automated_operations/ -> https://github.com/keptn/keptn.github.io/pull/815
- [ ] Spec: 
  - [ ] Could we solve: https://github.com/keptn/spec/issues/59 -> no
  - [x] https://github.com/keptn/spec/blob/master/cloudevents.md#remediation should be replaced (handled via https://github.com/keptn/keptn/pull/4085 and https://github.com/keptn/spec/pull/79 )

**Comment by christian-kreuzberger-dtx** [comment]
> Could we solve: keptn/spec#59

No, we have not streamlined problem events at all. The key difference between Keptn 0.7 and Keptn 0.8.3 will be that we no longer need `problem.open` events for the self-healing with Dynatrace use-case. A `problem` event is sent from Dynatrace via the Keptn API to dynatrace-service, which converts it into a `remediation.triggered` event (see https://github.com/keptn-contrib/dynatrace-service/issues/287 ).

If anything, we can most likely remove `problem.open` events from all our implementations and the spec, but that's about it.

> https://github.com/keptn/spec/blob/master/cloudevents.md#remediation should be replaced

Should be **removed**, as we don't have remediation events any more. Instead we have `get-action` events now, they are also missing.

**Comment by christian-kreuzberger-dtx** [comment]
I believe everything of this task is done, I have linked the respective PRs or wrote my answer to questions in the original issue above.

**Comment by christian-kreuzberger-dtx** [comment]
The PR on tutorials still needs to be merged once 0.8.3 is out.
